CREATE DATABASE ProyectoDWES_08;

USE ProyectoDWES_08;

--TABLA DE USUARIOS
CREATE TABLE USERS(
    EMAIL VARCHAR (255) PRIMARY KEY,
    USERNAME VARCHAR(100) REQUIRED NOT NULL,
    PHONE_NUMBER VARCHAR(20) REQUIRED NOT NULL,
    PASSWORD_USER VARCHAR(255) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
);
--TABLA DE COCHES
CREATE TABLE CARS(
    ID_CAR VARCHAR(8) PRIMARY KEY NOT NULL,
    FIRM VARCHAR(255) NOT NULL,
    MODEL VARCHAR(255) NOT NULL,
    YEAR_OF_CAR INT NOT NULL,
    DAY_PRICE DECIMAL( 10,2) NOT NULL,
    AVAIBLE BOOLEAN DEFAULT TRUE,
);