CREATE DATABASE ProyectoDWES_08;

USE ProyectoDWES_08;

--TABLA DE USUARIOS
CREATE TABLE USERS(
    EMAIL VARCHAR (255) PRIMARY KEY,
    USERNAME VARCHAR(100) REQUIRED,
    PHONE_NUMBER VARCHAR(20) REQUIRED,
    PASSWORD_USER VARCHAR(255)
    CREATED_AT DATE
);
--TABLA DE COCHES
CREATE TABLE CARS(
    ID_CAR VARCHAR(8) PRIMARY KEY,
    FIRM VARCHAR(255),
    MODEL VARCHAR(255),
    YEAR
);